apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: service
  name: ${GATEWAY_NAME}
spec:
  replicas: 1  
  strategy:
    type: Recreate 
  selector:
    matchLabels:
      app: ${GATEWAY_NAME}
  template:
    metadata:
      labels:
        app: ${GATEWAY_NAME}
    spec:
      containers:
      - name: ${GATEWAY_NAME}
        image: xedll/gateway-service:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: ${GATEWAY_SERVICE_PORT}
        env:
        - name: SESSION_SERVICE_HOST
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: SESSION_SERVICE_HOST
        - name: SESSION_SERVICE_PORT
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: SESSION_SERVICE_PORT
        - name: HOTEL_SERVICE_HOST
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: HOTEL_SERVICE_HOST
        - name: HOTEL_SERVICE_PORT
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: HOTEL_SERVICE_PORT
        - name: BOOKING_SERVICE_HOST
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: BOOKING_SERVICE_HOST
        - name: BOOKING_SERVICE_PORT
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: BOOKING_SERVICE_PORT
        - name: PAYMENT_SERVICE_HOST
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: PAYMENT_SERVICE_HOST
        - name: PAYMENT_SERVICE_PORT
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: PAYMENT_SERVICE_PORT
        - name: LOYALTY_SERVICE_HOST
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: LOYALTY_SERVICE_HOST
        - name: LOYALTY_SERVICE_PORT
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: LOYALTY_SERVICE_PORT
        - name: REPORT_SERVICE_HOST
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: REPORT_SERVICE_HOST
        - name: REPORT_SERVICE_PORT
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: REPORT_SERVICE_PORT
        - name: AUTH_TOKEN
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: AUTH_TOKEN
---
apiVersion: v1
kind: Service
metadata:
  namespace: service
  name: ${GATEWAY_NAME}
spec:
  selector:
    app: ${GATEWAY_NAME}
  ports:
  - port: ${GATEWAY_SERVICE_PORT}
    targetPort: ${GATEWAY_SERVICE_PORT}