apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: service
  name: ${PAYMENT_NAME}
spec:
  replicas: 1
  strategy:
    type: Recreate 
  selector:
    matchLabels:
      app: ${PAYMENT_NAME}
  template:
    metadata:
      labels:
        app: ${PAYMENT_NAME}
    spec:  
      containers:
      - name: ${PAYMENT_NAME}
        image: xedll/payment-service:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: ${PAYMENT_SERVICE_PORT}
        env:
        - name: POSTGRES_HOST
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: POSTGRES_HOST
        - name: POSTGRES_PORT
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: POSTGRES_PORT
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: POSTGRES_PASSWORD
        - name: POSTGRES_DB
          value: "payments_db"
        - name: AUTH_TOKEN
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: AUTH_TOKEN
---
apiVersion: v1
kind: Service
metadata:
  namespace: service
  name: ${PAYMENT_NAME}
spec:
  selector:
    app: ${PAYMENT_NAME}
  ports:
  - port: ${PAYMENT_SERVICE_PORT}
    targetPort: ${PAYMENT_SERVICE_PORT}