apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: service
  name: ${RABBIT_NAME}
spec:
  replicas: 1
  strategy:
    type: Recreate 
  selector:
    matchLabels:
      app: ${RABBIT_NAME}
  template:
    metadata:
      labels:
        app: ${RABBIT_NAME}
    spec:
      containers:
      - name: ${RABBIT_NAME}
        image: rabbitmq:3-management-alpine
        ports:
        - containerPort: ${RABBIT_MQ_PORT}
        - containerPort: ${RABBIT_MQ_PORT_UI}
        env:
        - name: RABBITMQ_DEFAULT_USER
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: RABBIT_MQ_USER
        - name: RABBITMQ_DEFAULT_PASS
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: RABBIT_MQ_PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  namespace: service
  name: ${RABBIT_NAME}
spec:
  selector:
    app: ${RABBIT_NAME}
  ports:
  - name: amqp
    port: ${RABBIT_MQ_PORT}
    targetPort: ${RABBIT_MQ_PORT}
  - name: management
    port: ${RABBIT_MQ_PORT_UI}
    targetPort: ${RABBIT_MQ_PORT_UI}