upstream gateway-service {
    server mystack_gateway:8087;
}

upstream booking-service {
    server mystack_booking:8083;
}

upstream session-service {
    server mystack_session:8081;
}
upstream rabbit-service {
    server mystack_rabbit:15692;
}



server {
    listen 8081;

    location / {
        proxy_pass http://session-service;
        proxy_set_header Host "localhost:8081";
    }
}

server {
    listen 8083;

    location / {
        proxy_pass http://booking-service;
        proxy_set_header Host "localhost:8083";
    }
}

server {
    listen 8087;

    location / {
        proxy_pass http://gateway-service;
        proxy_set_header Host "localhost:8087";
    }
}

server {
    listen 15692;

    location / {
        proxy_pass http://rabbit-service;
        proxy_set_header Host "localhost:15692";
    }
}

