upstream gateway-service {
    server mystackgateway:8087;
}


server {
    listen 8087;

    location / {
        proxy_pass http://gateway-service;
        proxy_set_header Host "localhost:8087";
    }
}
upstream session-service {
    server mystacksession:8081;
}

server {
    listen 8081;

    location / {
        proxy_pass http://session-service;
        proxy_set_header Host "localhost:8081";
    }
}