apiVersion: v1
kind: PersistentVolume
metadata:
    name: postgres-pv
    labels:
        type: local
spec:
    capacity:
        storage: 5Gi
    accessModes:
        - ReadWriteOnce
    persistentVolumeReclaimPolicy: Retain
    storageClassName: manual
    hostPath:
        path: "/mnt/data/postgres"
        type: DirectoryOrCreate

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: postgres-pvc
    namespace: service
spec:
    accessModes:
        - ReadWriteOnce
    storageClassName: manual
    resources:
        requests:
            storage: 5Gi
