apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
    name: gateway-service-monitor
    namespace: service
spec:
    selector:
        matchLabels:
            app: gateway-service
    endpoints:
        - port: http
          path: /metrics
          interval: 30s
