---
- name: Setup Apache web server
  hosts: apache
  become: yes
  roles:
    - apache

- name: Setup PostgreSQL database
  hosts: postgres
  become: yes
  roles:
    - postgres

- name: Setup Service web server
  hosts: application
  become: yes
  roles:
    - application