---
consul_version: "1.17.3"
envoy_version: "1.27.7"
consul_architecture: "x86_64"
consul_download_url: "https://releases.hashicorp.com/consul/{{ consul_version }}/consul_{{ consul_version }}_linux_{{ consul_architecture }}.zip"
envoy_download_url: "https://github.com/envoyproxy/envoy/releases/download/v1.27.7/envoy-1.27.7-linux-x86_64"
consul_zip_name: "consul_1.17.3_linux_amd64.zip"
consul_user: "consul"
consul_group: "consul"
consul_config_dir: "/etc/consul.d"
consul_data_dir: "/opt/consul"