{{- if .Values.postgresPV.enabled }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.postgresPV.name }}
  labels:
    type: local
spec:
  capacity:
    storage: {{ .Values.postgresPV.capacity }}
  accessModes:
    {{- toYaml .Values.postgresPV.accessModes | nindent 4 }}
  persistentVolumeReclaimPolicy: {{ .Values.postgresPV.persistentVolumeReclaimPolicy }}
  storageClassName: {{ .Values.postgresPV.storageClassName }}
  hostPath:
    path: {{ .Values.postgresPV.hostPath }}
    type: DirectoryOrCreate
{{- end }}