apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: service
  name: gateway-service
spec:
  replicas: 1  
  strategy:
    type: Recreate 
  selector:
    matchLabels:
      app: gateway-service
  template:
    metadata:
      labels:
        app: gateway-service
    spec:
      containers:
      - name: gateway-service
        image: xedll/gateway-service:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8087
        env:
        - name: SESSION_SERVICE_HOST
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: SESSION_SERVICE_HOST
        - name: SESSION_SERVICE_PORT
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: SESSION_SERVICE_PORT
        - name: HOTEL_SERVICE_HOST
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: HOTEL_SERVICE_HOST
        - name: HOTEL_SERVICE_PORT
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: HOTEL_SERVICE_PORT
        - name: BOOKING_SERVICE_HOST
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: BOOKING_SERVICE_HOST
        - name: BOOKING_SERVICE_PORT
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: BOOKING_SERVICE_PORT
        - name: PAYMENT_SERVICE_HOST
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: PAYMENT_SERVICE_HOST
        - name: PAYMENT_SERVICE_PORT
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: PAYMENT_SERVICE_PORT
        - name: LOYALTY_SERVICE_HOST
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: LOYALTY_SERVICE_HOST
        - name: LOYALTY_SERVICE_PORT
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: LOYALTY_SERVICE_PORT
        - name: REPORT_SERVICE_HOST
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: REPORT_SERVICE_HOST
        - name: REPORT_SERVICE_PORT
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: REPORT_SERVICE_PORT
        - name: AUTH_TOKEN
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: AUTH_TOKEN
---
apiVersion: v1
kind: Service
metadata:
  namespace: service
  name: gateway-service
spec:
  selector:
    app: gateway-service
  ports:
  - port: 8087
    targetPort: 8087