apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: service
  name: hotel-service
spec:
  replicas: 1
  strategy:
    type: Recreate 
  selector:
    matchLabels:
      app: hotel-service
  template:
    metadata:
      labels:
        app: hotel-service
    spec:
      containers:
      - name: hotel-service
        image: xedll/hotel-service:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8082
        env:
        - name: POSTGRES_HOST
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: POSTGRES_HOST
        - name: POSTGRES_PORT
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: POSTGRES_PORT
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: POSTGRES_PASSWORD
        - name: POSTGRES_DB
          value: "hotels_db"
        - name: AUTH_TOKEN
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: AUTH_TOKEN
---
apiVersion: v1
kind: Service
metadata:
  namespace: service
  name: hotel-service
spec:
  selector:
    app: hotel-service
  ports:
  - port: 8082
    targetPort: 8082