apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: service
  name: loyalty-service
spec:
  replicas: 1
  strategy:
    type: Recreate 
  selector:
    matchLabels:
      app: loyalty-service
  template:
    metadata:
      labels:
        app: loyalty-service
    spec:
      containers:
      - name: loyalty-service
        image: xedll/loyalty-service:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8085
        env:
        - name: POSTGRES_HOST
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: POSTGRES_HOST
        - name: POSTGRES_PORT
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: POSTGRES_PORT
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: POSTGRES_PASSWORD
        - name: POSTGRES_DB
          value: "balances_db"
        - name: AUTH_TOKEN
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: AUTH_TOKEN
---
apiVersion: v1
kind: Service
metadata:
  namespace: service
  name: loyalty-service
spec:
  selector:
    app: loyalty-service
  ports:
  - port: 8085
    targetPort: 8085