apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: service
  name: report-service
spec:
  replicas: 1
  strategy:
    type: Recreate 
  selector:
    matchLabels:
      app: report-service
  template:
    metadata:
      labels:
        app: report-service
    spec:
      containers:
      - name: report-service
        image: xedll/report-service:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8086
        env:
        - name: POSTGRES_HOST
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: POSTGRES_HOST
        - name: POSTGRES_PORT
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: POSTGRES_PORT
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: POSTGRES_PASSWORD
        - name: POSTGRES_DB
          value: "statistics_db"
        - name: RABBIT_MQ_HOST
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: RABBIT_MQ_HOST
        - name: RABBIT_MQ_PORT
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: RABBIT_MQ_PORT
        - name: RABBIT_MQ_USER
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: RABBIT_MQ_USER
        - name: RABBIT_MQ_PASSWORD
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: RABBIT_MQ_PASSWORD
        - name: RABBIT_MQ_QUEUE_NAME
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: RABBIT_MQ_QUEUE_NAME
        - name: RABBIT_MQ_EXCHANGE
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: RABBIT_MQ_EXCHANGE
        - name: AUTH_TOKEN
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: AUTH_TOKEN
---
apiVersion: v1
kind: Service
metadata:
  namespace: service
  name: report-service
spec:
  selector:
    app: report-service
  ports:
  - port: 8086
    targetPort: 8086